
const data = [{
    key: '1',
    name: '石家庄桥牌锦标赛',
    signEndTime: '2017-05-04',
    start_time: '2017-08-02',
    over_time: '2017-08-05',
    referee:'裁判',
    arbitrator: '仲裁',
    host_unit: '主办方',
    undertaking_unit: '赞助商',
    cooperating_unit: '承办',
    state:'待审核',
}, {
    key: '2',
    name: '石家庄桥牌团体赛',
    signEndTime: '2017-05-04',
    start_time: '2017-05-04',
    over_time: '2017-08-05',
    referee:'裁判',
    arbitrator: '仲裁',
    host_unit: '主办方',
    undertaking_unit: '赞助商',
    cooperating_unit: '承办',
    state:'待审核',
}, {
    key: '3',
    name: '宏鸿杯桥牌锦标赛',
    signEndTime: '2017-05-04',
    start_time: '2017-05-04',
    over_time: '2017-08-05',
    referee:'裁判',
    arbitrator: '仲裁',
    host_unit: '主办方',
    undertaking_unit: '赞助商',
    cooperating_unit: '承办',
    state:'待审核',
}, {
    key: '4',
    name: '鹿泉桥牌锦标赛',
    signEndTime: '2017-05-04',
    start_time: '2017-05-04',
    over_time: '2017-08-05',
    referee:'裁判',
    arbitrator: '仲裁',
    host_unit: '主办方',
    undertaking_unit: '赞助商',
    cooperating_unit: '承办',
    state:'待审核',
}
,{
    key: '5',
    name: '沧州桥牌锦标赛',
    signEndTime: '2017-05-04',
    start_time: '2017-05-04',
    over_time: '2017-08-05',
    referee:'裁判',
    arbitrator: '仲裁',
    host_unit: '主办方',
    undertaking_unit: '赞助商',
    cooperating_unit: '承办',
    state:'待审核',
},
{
    key: '6',
    name: '邢台桥牌锦标赛',
    signEndTime: '2017-05-04',
    start_time: '2017-05-04',
    over_time: '2017-08-05',
    referee:'裁判',
    arbitrator: '仲裁',
    host_unit: '主办方',
    undertaking_unit: '赞助商',
    cooperating_unit: '承办',
    state:'待审核',
},{
    key: '7',
    name: '河北桥牌锦标赛',
    signEndTime: '2017-05-04',
    start_time: '2017-05-04',
    over_time: '2017-08-05',
    referee:'裁判',
    arbitrator: '仲裁',
    host_unit: '主办方',
    undertaking_unit: '赞助商',
    cooperating_unit: '承办',
    state:'待审核',
},
];
export default data;
